install.packages("fitdistrplus",dependencies=T)
install.packages("plyr")
library(rJava)
library(KoNLP)
library(wordcloud)
library(plyr)
library(twitteR)
library(tm)
library(RColorBrewer)
library(Unicode)
library(RMySQL)
con = dbConnect(MySQL(), user='rnduser', password='hongik_gwh', dbname='falling', host='52.79.138.56')
dbSendQuery(con, 'set names utf8')
query.result<-dbSendQuery(con,"select message from MindView")
test.table <- fetch(query.result,n=-1)
write.table(test.table,"mySQLdata.txt",row.names = F)
#query.result<-dbSendQuery(con,"select M.message from UserView U, MindView M where M.userId=U.userId and U.gender=1")
#write.table(test.table,"mydata.txt",row.names=F)

txt=readLines("mySQLdata.txt",encoding = "UTF-8")
txt=gsub("??","",txt)
xt=gsub("'","",txt)
nouns = sapply(txt, extractNoun, USE.NAMES=F)
nouns_unlist = unlist(nouns) 
head(nouns_unlist,30) 
txt_2 = Filter(function(x) {nchar(x) >=2},nouns_unlist)#2WORD!
head(txt_2, 30) 
write(txt_2, "2WORD.txt") 
rev <- read.table("2WORD.txt")
nrow(rev) 
table(rev)
wordcount = table(rev)
head(sort(wordcount, decreasing=T),30)
wordcount<-table(unlist(nouns))
wordcount<-sort(wordcount, decreasing=T)
write.csv(wordcount,"wordcount.csv")
windows()
palete = brewer.pal(9,"Set1") 
wordcloud(names(wordcount), freq=wordcount, scale=c(5,.5), rot.per= .25, min.freq=1, random.order=F, random.color = T, colors=palete)
savePlot("alert_2.jpg",type="jpg")